import { NextPage } from "next";
import Head from "next/head";
import UserLayout from "../../layoutes/UserLayout";

const Todo: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Todo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserLayout>test</UserLayout>
    </div>
  );
};

export default Todo;
